name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint & Format
        run: npm run lint && npm run format
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test -- --coverage
      - name: Test Egress Optimization
        run: |
          # Simple egress test: check if queries are cached
          npm run build
          # Mock test for egress (placeholder)
          echo "Egress test passed - implement actual load test with Artillery if needed"
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
      - name: Deploy (Opsional)
        if: github.ref == 'refs/heads/main'
        run: echo "Deploy step di sini (integrasi Vercel/Netlify/Custom)"
